### ISSUE TITLE
--exclude should allow excluding metapackages

### ISSUE THREAD

**Issue by gordonbrander** [ros-infrastructure/rosinstall_generator#39]
## Use case

I am using some packages for which binaries are not available on my platform. For these, I would like to build from source, including only the catkin source packages for which there are not binaries.

For example, let's say I have installed `ros_comm` binary via `apt-get`. I would like to be able to:

    rosinstall_generator some_package --exclude ros_comm --rosdistro indigo --deps --wet-only --tar > example.rosinstall

...And get a `rosinstall` file that includes all package dependencies of `some_package`, but omits the the ros_comm metapackage.

## Current behavior

The `--exclude` flag only allows excluding individual ros packages, making it impractical to exclude a metapackage like `ros_comm`.

Unless you want to manually trim the generated package list, this makes building packages and dependencies from source all-or-nothing, as far as I can tell.

**Comment by wjwwood** [comment]
If you have `ros_comm` (and its dependencies) installed, you can add them to your `ROS_PACKAGE_PATH` (either manually or by sourcing a setup file) and use `--exclude RPP`. Does this not address the "from source all-or-nothing" concern you had?

**Comment by gordonbrander** [comment]
@wjwwood this works for `apt-get` installed packages too? I had the impression `ROS_PACKAGE_PATH` only pointed to src catkin packages.

**Comment by wjwwood** [comment]
@gordonbrander nope, if you source `/opt/ros/<rosdistro>/setup.bash` and check your `ROS_PACKAGE_PATH` it will contain a folder in `/opt/ros/<rosdistro>`.

**Comment by mikepurvis** [comment]
You can also confirm the list of "seen packages" by running `rospack list` in your current environment.

**Comment by gordonbrander** [comment]
That's fantastic! Thanks for bearing with... I'm relatively new to the ROS stack.

**Comment by wjwwood** [comment]
No worries, the other issue with your suggestion (as not to discard it out of hand) is determining which `ros_comm` you want to use for recursive dependencies. You could get the latest released version from ros/rosdistro but you might also want to use a version that hasn't been released yet, that you might have locally or might be elsewhere. Unfortunately, it's always a little more tricky that it sounds at first to implement most things.

You could imagine an option like `--exclude-with-deps <single package>` and that package would be used locally if it's on the RPP, and if not it could look to ros/rosdistro, and if not there too throw an error. But given the workaround provided by `--exclude RPP`, it seems low priority.
