### ISSUE TITLE
Remove groovy specific code

### ISSUE THREAD

**Issue by russkel** [ros-infrastructure/rosinstall_generator#55]
There's a few blocks of code that reference the groovy distribution explicitly. Seeing as it is end-of-lifed, should it be removed in the interest of good house keeping?

https://github.com/ros-infrastructure/rosinstall_generator/blob/a14f819516a59fe2449fdb84975e7fa10073c729/src/rosinstall_generator/generator.py#L125

https://github.com/ros-infrastructure/rosinstall_generator/blob/a14f819516a59fe2449fdb84975e7fa10073c729/src/rosinstall_generator/generator.py#L186

https://github.com/ros-infrastructure/rosinstall_generator/blob/a14f819516a59fe2449fdb84975e7fa10073c729/src/rosinstall_generator/generator.py#L228

**Comment by tfoote** [comment]
We generally like to keep backwards compatibility beyond EOL if possible. This is especially true for tools like this which are important for the building from source toolchain that the use of EOL distros requires. Though now that we're EOLing Indigo we could likely make that choice as groovy is now very deprecated.

Overall though this logic and all the wet/dry logic is all based on mixing rosbuild and catkin packages in a distro. And at some point we should probably choose to remove support for that which will will remove all dry vs wet code paths. So if we were to do a cleanup that would be reasonable. And we are approaching 5 years after Groovy EOL which is probably a reasonable amount of backwards compatibility maintain. So a removal of the wet vs dry logic is something that we could consider doing.

**Comment by dirk-thomas** [comment]
If we get to the point to remove `rosbuild` support from all packages / infrastructure these parts can certainly be removed. Hopefully that will be something attempted before ROS Noetic in May 2020.

Just in "interest of good house keeping" I don't think we should remove them right now. Therefore I will go ahead and close this ticket for now.
