### ISSUE TITLE
`rosinstall_generator ALL` doesn't list anything after 0.1.17 release

### ISSUE THREAD

**Issue by seanyen** [ros-infrastructure/rosinstall_generator#59]
After I upgraded `rosinstall_generator` into `0.1.17`, `rosinstall_generator ALL` stops listing all the repositories, and instead it only shows `No packages/stacks left after ignoring unreleased`.

**Comment by dirk-thomas** [comment]
This looks like a regression of #56. @sloretz Can you please look into this asap.
