### ISSUE TITLE
fails to resolve gitlab urls containing dots

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/rosinstall_generator#63]
How to reproduce:

```
docker run -it --rm ros:melodic
apt -qq update && apt -qq install -y python-rosinstall-generator python3-vcstool
cd && mkdir src 
rosinstall_generator autoware_msgs --tar > repos
vcs import src < repos
Tarball requested for repo 'autoware_msgs/autoware_msgs', but I can't parse git URL 'https://gitlab.com/autowarefoundation/autoware.ai-ros-releases/messages-release.git'.
Falling back on git clone for repo 'autoware_msgs/autoware_msgs'.
```

Most likely this regex https://github.com/ros-infrastructure/rosinstall_generator/blob/34923142fd8e080fe3404cae8308633551cee7b4/src/rosinstall_generator/distro.py#L155 is too restrictive

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request.

**Comment by dirk-thomas** [comment]
@mikaelarguedas Friendly ping. Are you still interested in supporting this use case?

**Comment by mikaelarguedas** [comment]
This is an issue that surfaced when I was working on https://github.com/ros/rosdistro/pull/23844 but not one I'm impacted by on a daily basis so I most likely won't commit time to provide a fix.
