### ISSUE TITLE
Python2 dependency issue in kinetic

### ISSUE THREAD

**Issue by adam-pensa** [ros-infrastructure/rosinstall_generator#69]
I receive the following error when attempting to install rosinstall_generator using apt. Error message:
```
The following packages have unmet dependencies:
 python-rosinstall-generator : Depends: python2 (< 2.8) but it is not installable
                               Depends: python2 (>= 2.7) but it is not installable
                               Depends: python2:any (>= 2.6.6-7~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Steps to reproduce on Ubuntu 18.04:
```bash
docker pull osrf/ros:kinetic-desktop-full-xenial
docker run -it  osrf/ros:kinetic-desktop-full-xenial /bin/bash
root@f5af8e84cfb3:/# sudo apt update
root@f5af8e84cfb3:/# sudo apt install python-rosinstall-generator
```
which gives output:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-rosinstall-generator : Depends: python2 (< 2.8) but it is not installable
                               Depends: python2 (>= 2.7) but it is not installable
                               Depends: python2:any (>= 2.6.6-7~) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by dirk-thomas** [comment]
Thanks for the report. This was a bug in the packaging process. Version 0.1.21 has been released which resolves this. It should be available soonish in the apt repos.

**Comment by ssagrawal01** [comment]
Hello @dirk-thomas, I am encountering what looks like an identical issue in melodic. Is this also part of the fix which is coming out? Many thanks!

**Comment by dirk-thomas** [comment]
@ssagrawal01 Python packages like this are not specific to a ROS distribution. So the new version fixing the packaging problem should already be available on Ubuntu Bionic.

**Comment by Sanderi44** [comment]
Having the same problem in Ubuntu 16.04 with ROS Kinetic.

**Comment by dirk-thomas** [comment]
> Having the same problem in Ubuntu 16.04 with ROS Kinetic.

@Sanderi44 Did you run the commands mentioned in the original description:

```
sudo apt update
sudo apt install python-rosinstall-generator
```

If the problem persists for you after that please consider posting more information.

**Comment by Sanderi44** [comment]
Yes. This is running in our CI, so it always updates before installing.

**Comment by ssagrawal01** [comment]
Hi @dirk-thomas,

Thanks for the earlier reply. I am continuing to experience the issue above. I just ran it a couple minutes ago.

Here's the trace from my running the second of the two commands:

     Reading package lists... Done`
     Building dependency tree       
     Reading state information... Done
     Some packages could not be installed. This may mean that you have
     requested an impossible situation or if you are using the unstable
     distribution that some required packages have not yet been created
     or been moved out of Incoming.
     The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
    python-rosinstall-generator : Depends: python2 (< 2.8) but it is not installable
                                   Depends: python2 (>= 2.7) but it is not installable
                                   Depends: python2:any (>= 2.6.6-7~) but it is not installable
    E: Unable to correct problems, you have held broken packages.
``

I recently uninstalled my prior kinetic installation (along with Gazebo, husarnet, and any traces of ros packages that I could find) and then did an upgrade from Ubuntu 16.04 to 18.04. I then followed the installation instructions for melodic, and all steps worked except for the above (I have tested up to roscore running successfully).

Any help would be greatly appreciated.

Thanks!

**Comment by dirk-thomas** [comment]
> Here's the trace from my running the second of the two commands:

@ssagrawal01 Please also share the output of the first of the two commands.

Please also post the output of `apt search python-rosinstall-generator`.

**Comment by NighttimeDriver50000** [comment]
At this time, it appears the new version is not on the packages.ros.org repo.

In http://packages.ros.org/ros/ubuntu/dists/bionic/main/binary-amd64/Packages for me right now:

```
Package: python-rosinstall-generator
Priority: optional
Section: python
Installed-Size: 74
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Architecture: all
Version: 0.1.20-1
Depends: python-catkin-pkg (>= 0.1.28), python-pkg-resources, python-rosdistro (>= 0.7.3), python-rospkg, python-yaml, python2 (<< 2.8), python2 (>= 2.7), python2:any (>= 2.6.6-7~), python-argparse
Conflicts: python3-rosinstall-generator
Filename: pool/main/p/python-rosinstall-generator/python-rosinstall-generator_0.1.20-1_all.deb
SHA512: 9fa3006d528a3dd122f8e9501f301bb0642e89522de73cad1aaf862325662a8bc482f2630fe757768cc2487da7e2f5f848eaaea1ed5da3bc3b65ad947bff4c0f
Size: 11440
SHA256: 9956ec884aa95a8f878305da4b9b4daf2336e507ffb3028d3cf341848bf70d42
SHA1: ee5964daa022ea72e50d62565406dc5fe23237e3
MD5sum: d3b491c0f199a92ac31d667fdb0f3eae
Description: A tool for generating rosinstall files
 A tool for generating rosinstall files
```

Maybe it's a CDN thing? Is there another package repo that the new version has been pushed into?

**Comment by ssagrawal01** [comment]
Here's the output of running the first command: `sudo apt update`
```
Hit:1 http://packages.ros.org/ros/ubuntu bionic InRelease
Get:2 http://dl.google.com/linux/chrome/deb stable InRelease [1,811 B]         
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic InRelease                     
Get:5 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,125 B]
Get:6 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]   
Get:7 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB] 
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [46.0 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11 Metadata [295 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [49.1 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 DEP-11 Metadata [2,464 B]
Get:12 http://us.archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [69.8 kB]
Get:13 http://us.archive.ubuntu.com/ubuntu bionic-updates/restricted i386 Packages [11.2 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [1,023 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,086 kB]
Get:16 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 DEP-11 Metadata [279 kB]
Get:17 http://us.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 DEP-11 Metadata [2,468 B]
Get:18 http://us.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 DEP-11 Metadata [7,972 B]
Fetched 3,126 kB in 2s (1,624 kB/s)                                    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

Here's the result of running: `apt search python-rosinstall-generator`
```
Sorting... Done
Full Text Search... Done
python-rosinstall-generator/bionic,bionic 0.1.20-1 all
  A tool for generating rosinstall files

```

**Comment by dirk-thomas** [comment]
I got a different result (already before):

```
Package: python-rosinstall-generator
Priority: optional
Section: python
Installed-Size: 74
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Architecture: all
Version: 0.1.21-1
Depends: python-catkin-pkg (>= 0.1.28), python-pkg-resources, python-rosdistro (>= 0.7.3), python-rospkg, python-yaml, python (<< 2.8), python (>= 2.7), python:any (>= 2.6.6-7~), python-argparse
Conflicts: python3-rosinstall-generator
Filename: pool/main/p/python-rosinstall-generator/python-rosinstall-generator_0.1.21-1_all.deb
SHA512: 57bcff1056869c5d90afe752d839b50a13992d820dd8c4e9cfb06b5a04f577eaaac6a0bcd3c0f6f8afc99a93068b053b4753907d2ee0ddf3c52d7409046cec5b
Size: 11444
SHA256: 2dda354e46bfb4f9e49fa6f40bb27ae212434cd7d9af8be0e0e5aa150bd7b844
SHA1: ee3e3dcba8ca52f5e4ff6d076fde6d7309b7360f
MD5sum: 969a1507df0293dee4c75557b78c21a4
Description: A tool for generating rosinstall files
 A tool for generating rosinstall files
```

It could be that one of the mirrors didn't update correctly. I just poke the re-deploy job. Hopefully that helps.

**Comment by ssagrawal01** [comment]
@dirk-thomas it worked now! Thank you **very much** for your help!

**Comment by dirk-thomas** [comment]
> Is there another package repo that the new version has been pushed into?

There are multiple levels involved. Without to much detail:
* the Python package gets pushed into a bootstrap repo
* from there a Jenkins job pushes it into the apt repos used by the buildfarm
* from there a Jenkins job pushes the packages to the servers at Oregon State University
* which then has there own set of mirrors...

**Comment by NighttimeDriver50000** [comment]
Ah, that makes sense. Running `apt clean && apt update` fixed it for me, so it was some sort of caching issue. Thanks!

**Comment by Sanderi44** [comment]
Looks like the poking of the re-deploy worked for me!
