### ISSUE TITLE
Package snapshot at point in time

### ISSUE THREAD

**Issue by oysstu** [ros-infrastructure/rosinstall_generator#94]
I'd like to generate a rosinstall at a point in time, particularly the versions matching the [ros2 releases](https://github.com/ros2/ros2/releases). As described on [stack exchange](https://robotics.stackexchange.com/questions/101259/how-are-the-repos-yaml-files-generated), the ros2.repos in the ros2 repo is a subset of packages intended for CI, and does for example not contain all the repositories necessary to compile the [perception variant metapackage](https://github.com/ros2/variants).

My instinct is to generate the rosinstall for the latest packages and look at the timestamps of the gbp release tags. However, this does not work if the most recent release has removed a dependency. A robust solution would generate the dependency tree at a certain point in time. Any thoughts on the best way to accomplish this?

**Comment by gavanderhoorn** [comment]
A bit late, but perhaps could still be useful.

I don't know whether it covers your requirement(s) completely, but for a research project we had a similar requirement/desire and created [rosin-project/rosinstall_generator_time_machine](https://github.com/rosin-project/rosinstall_generator_time_machine).

**Comment by mikepurvis** [comment]
We handle this by snapshotting and tagging the rosdistro itself, eg:

https://github.com/ros-infrastructure/rosdistro/blob/master/src/rosdistro/cli/rosdistro_freeze_source.py

Then colcon-distro's server/generator components provide the snapshot-aware replacement for rosinstall-generator:

https://colcon-distro.readthedocs.io/en/latest/overview.html

https://github.com/clearpathrobotics/colcon-distro/blob/main/colcon_distro/generate.py

**Comment by tfoote** [comment]
If you want to go back in time the distro snapshot/specific checkout is likely the best way to do it. You can set your ROSDISTRO_INDEX_URL to your fork/snapshot and generate against that without any changes necessary to this generator. 

If you have a checkout on your current system you want to be able to preserve for the future. I recommend using `vcs export --exact` on your workspace.

**Comment by gavanderhoorn** [comment]
> If you want to go back in time the distro snapshot/specific checkout is likely the best way to do it. You can set your ROSDISTRO_INDEX_URL to your fork/snapshot and generate against that without any changes necessary to this generator.

yes, that's exactly what `rosinstall_generator_time_machine` does. It just automates it a bit.

**Comment by oysstu** [comment]
Great thank you all for the tips. Making a snapshot seems like the most convenient way to go about this.

**Comment by gavanderhoorn** [comment]
Note that no matter how you do it, you'll always have the problem/challenge you're (re)building a version of those packages against an OS which most likely *did* see changes/updates in the time between 'now' and the state of the `rosdistro` you go back to.

We haven't really found a way to do something about that though.
