### ISSUE TITLE
Broken install on Ubuntu 24.04

### ISSUE THREAD

**Issue by sgstreet** [ros-infrastructure/rosinstall_generator#96]
I tried to install on Ubuntu 24.04 and got this error message:

```
sudo apt-get install python-rosinstall-generator
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-rosinstall-generator is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-rosinstall-generator' has no installation candidate
```

My apt source file is:

```
deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu noble main
```

Is this expected to be availailable for ros2 jazzy?

**Comment by cottsay** [comment]
> Is this expected to be availailable for ros2 jazzy?

It is not. This is the expected behavior. `python-rosinstall-generator` refers to the Python 2 package. Python 2 reached EOL in 2020, and as such, rosinstall_generator no longer supports it.

On Jazzy, you should install the Python 3 package, `python3-rosinstall-generator`.

**Comment by sgstreet** [comment]
Of course. Sorry for the total loss of brain function.
